services:
  mysql:
    image: mysql:8.0
    container_name: baozi_store_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: baozi_store
    ports:
      - "3307:3307"
    volumes:
      - baozi_mysql_data:/var/lib/mysql

volumes:
  baozi_mysql_data:
